# Generated by Django 5.0.1 on 2024-02-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_promotion',
            field=models.BooleanField(default=False, verbose_name='Промо карусель'),
        ),
    ]
